# Generated by Django 5.2.6 on 2025-10-11 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RectCard',
            fields=[
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('color', models.CharField()),
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('dueDate', models.CharField()),
                ('status', models.CharField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectCard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
