# Generated by Django 5.1.7 on 2025-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectcard',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rectcard',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rectcard',
            name='dueDate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rectcard',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rectcard',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rectcard',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
